spring:
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 5000
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  flyway:
    enabled: false
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sesa4?useTimezone=true&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 600000
jwt:
  secret: 2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
external-token: 85e059a0-e529-4285-815b-c32130cc278f
server:
  error:
    include-message: always
  port: 8080
application-address: http://localhost:4200